# 配置文件中的原来存在的facility子键不要删除，硬配置
main:
  hexcode_normal: '&#FBB6B6'
  hexcode_bossbar: '&#E0E6FB'
  hexcode_actionbar: '&#E0E6FB'
facility:
  teapan:
    namespace: 'grxi:teapan'
    custom_model_data: 10014
    # 这里是激活触发的物品 默认都为paper 没引入原版物品
    acquire_items:
      # 下文可自行添加
      matcha_leaf:
        custom_model_data: 10022
        amount: 3
    waitting_times: 3
    condition:
      weather: 'rain'