name: FacilityProp
main: com.github.cinnaio.facilityprop.FacilityProp
version: '${version}'
api-version: '1.20'
author: Cinnaio
depend:
  - ItemsAdder
commands:
  facilityprop:
    aliases:
      - "prop"
      - "fp"