name: FacilityProp
version: '2.0.0'
main: com.github.cinnaio.facilityprop.FacilityProp
api-version: '1.20'
author: 'Cinnaio'
softdepend: ['ItemsAdder', 'Vault']
depend: ['Vault']
commands:
  facilityprop:
    aliases: ['fp']