name: FacilityProp
version: '3.0.0'
main: com.github.cinnaio.facilityprop.FacilityProp
api-version: '1.21'
author: 'Cinnaio'
softdepend: ['ItemsAdder']
depend: ['Vault']
commands:
  facilityprop:
    aliases: ['fp']
permissions:
  facilityprop.command.reload:
    description: '插件重载'
  facilityprop.command.list:
    description: '查看定义设备数量'